version: '3.9'

services:
  mongo_db:
    image: mongo:7.0.5
    container_name: bang_mongo_db
    restart: always
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
      - MONGO_INITDB_DATABASE=${DB_NAME}
    ports:
      - '${DB_PORT}:${DB_PORT}'

  redis:
    image: redis:6
    container_name: bang_redis
    restart: on-failure
    volumes:
      - redis-data:/data/redis
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'
    expose:
      - '${REDIS_PORT}'
    command: '--port ${REDIS_PORT}'

  api:
    container_name: bang_api
    build: .
    ports:
      - '${PORT}:${PORT}'
    environment:
      MONGODB_URI: 'mongodb://${DB_HOST}:${DB_PORT}/${DB_NAME}?authSource=admin'
    volumes:
      - .:/src
    depends_on:
      - mongo_db
      - redis

volumes:
  mongo-data:
  redis-data: