import { Player } from '../interfaces/player.interface';

export const players: Player[] = [
  {
    uuid: crypto.randomUUID(),
    socketId: null,
    userName: 'Player1',
    role: null,
    character: null,
    health: 0,
    weapon: null,
  },
  {
    uuid: crypto.randomUUID(),
    socketId: null,
    userName: 'Player2',
    role: null,
    character: null,
    health: 0,
    weapon: null,
  },
  {
    uuid: crypto.randomUUID(),
    socketId: null,
    userName: 'Player3',
    role: null,
    character: null,
    health: 0,
    weapon: null,
  },
  {
    uuid: crypto.randomUUID(),
    socketId: null,
    userName: 'Player4',
    role: null,
    character: null,
    health: 0,
    weapon: null,
  },
  {
    uuid: crypto.randomUUID(),
    socketId: null,
    userName: 'Player5',
    role: null,
    character: null,
    health: 0,
    weapon: null,
  },
  {
    uuid: crypto.randomUUID(),
    socketId: null,
    userName: 'Player6',
    role: null,
    character: null,
    health: 0,
    weapon: null,
  },
  {
    uuid: crypto.randomUUID(),
    socketId: null,
    userName: 'Player7',
    role: null,
    character: null,
    health: 0,
    weapon: null,
  },
];
